### Рассчитать среднее время пребывания

##### Дано 3 DataFrames

In [1]:
import pandas as pd

In [2]:
df1 = [
    {'page1': 1, 'page2': 25, 'page3': 3}, 
    {'page1': 4, 'page2': 58, 'page3': 1}, 
    {'page1': 1.5, 'page2': 8, 'page3': 0.5}
    ]

df2 = [
     {'page1': 2, 'page2': 11, 'page3': None}, 
     {'page1': 5, 'page2': 21, 'page3': 5}, 
     {'page1': 0.1, 'page2': 38, 'page3': 15}
     ]

df3 = [
     {'page1': 2, 'page2': 11, 'page3': 40}, 
     {'page1': 5, 'page2': 15, 'page3': None}, 
     {'page1': 4, 'page2': 21, 'page3': 13}
     ]

df1, df2, df3 = [pd.DataFrame(df) for df in [df1, df2, df3]]

In [3]:
df1

   page1  page2  page3
0    1.0     25    3.0
1    4.0     58    1.0
2    1.5      8    0.5

In [4]:
df2

   page1  page2  page3
0    2.0     11    NaN
1    5.0     21    5.0
2    0.1     38   15.0

In [5]:
df3

   page1  page2  page3
0      2     11   40.0
1      5     15    NaN
2      4     21   13.0

##### Задание:
- Объединить все датафреймы в один
- Удалить строки, где есть хотя бы один пропуск
- Добавить строку *Mean* в конец датафрейма, в которой будет рассчитано среднее значение по каждому из столбцов

**1. Объединяем DataFrames**

In [6]:
df = pd.concat((df1, df2, df3), axis=0, ignore_index=True)
df

   page1  page2  page3
0    1.0     25    3.0
1    4.0     58    1.0
2    1.5      8    0.5
3    2.0     11    NaN
4    5.0     21    5.0
5    0.1     38   15.0
6    2.0     11   40.0
7    5.0     15    NaN
8    4.0     21   13.0

**2. Удаляем NaN**

In [7]:
df.dropna(subset=['page1', 'page2', 'page3'], inplace=True)

In [8]:
df.reset_index(drop=True, inplace=True)
df

   page1  page2  page3
0    1.0     25    3.0
1    4.0     58    1.0
2    1.5      8    0.5
3    5.0     21    5.0
4    0.1     38   15.0
5    2.0     11   40.0
6    4.0     21   13.0

**3. Добавляем итоговую строку с расчетом среднего по каждому столбцу**

In [9]:
df.loc['Mean'] = df.mean()

In [10]:
df

         page1  page2      page3
0     1.000000   25.0   3.000000
1     4.000000   58.0   1.000000
2     1.500000    8.0   0.500000
3     5.000000   21.0   5.000000
4     0.100000   38.0  15.000000
5     2.000000   11.0  40.000000
6     4.000000   21.0  13.000000
Mean  2.514286   26.0  11.071429