### Объединить датафреймы по ключу

##### Дано 2 DataFrames

In [1]:
import pandas as pd

In [2]:
sales = [
    {'ProductID': 1, 'Amount': 5, 'Sum': 528},
    {'ProductID': 2, 'Amount': 2, 'Sum': 624}, 
    {'ProductID': 2, 'Amount': 1, 'Sum': 312}, 
    {'ProductID': 3, 'Amount': 1, 'Sum': 10}, 
    {'ProductID': 4, 'Amount': 8, 'Sum': 10842}, 
    {'ProductID': 4, 'Amount': 3, 'Sum': 4065}, 
    {'ProductID': 5, 'Amount': 1, 'Sum': 1024}
]


products = [
    {'ProductID': 1, 'ProductName': 'Apple'},
    {'ProductID': 2, 'ProductName': 'Mango'}, 
    {'ProductID': 3, 'ProductName': 'Banana'}, 
    {'ProductID': 4, 'ProductName': 'Orange'}
]

sales, products = pd.DataFrame(sales), pd.DataFrame(products)

In [3]:
sales

   ProductID  Amount    Sum
0          1       5    528
1          2       2    624
2          2       1    312
3          3       1     10
4          4       8  10842
5          4       3   4065
6          5       1   1024

In [4]:
products

   ProductID ProductName
0          1       Apple
1          2       Mango
2          3      Banana
3          4      Orange

##### Задание:
 - Объеденить dataframes по ключу. Если в правом df нет соответствий левому, вывести NaN (ключ - ProductID)

In [5]:
sales.merge(products, how='left', on='ProductID')

   ProductID  Amount    Sum ProductName
0          1       5    528       Apple
1          2       2    624       Mango
2          2       1    312       Mango
3          3       1     10      Banana
4          4       8  10842      Orange
5          4       3   4065      Orange
6          5       1   1024         NaN