### Динамика продаж

##### Дан датафрейм с продажами

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'sales': [100, 150, 150, 120, 135, 180, 230, 500, 501, 499, 500, 500]})
df

    sales
0     100
1     150
2     150
3     120
4     135
5     180
6     230
7     500
8     501
9     499
10    500
11    500

##### Задание:
К df добавить 2 новых столбца:
 - prev_sales - продажи за предыдущий период
 - inc - рост продаж по сравнению с предыдущим периодом
 
 Значения в столбце inc должны быть выражены в % и округлены до 2 знаков после запятой

**1. Добавляем столбец prev_sales со смещенными значениями на позицию вниз**

In [3]:
df['prev_sales'] = df.shift(1)
df

    sales  prev_sales
0     100         NaN
1     150       100.0
2     150       150.0
3     120       150.0
4     135       120.0
5     180       135.0
6     230       180.0
7     500       230.0
8     501       500.0
9     499       501.0
10    500       499.0
11    500       500.0

**2. Добавляем столбец inc. Рассчитываем рост текущих продаж к предыдущим и округляем до сотых**

In [4]:
df['inc'] = ((df['sales'] / df['prev_sales'] - 1) * 100).apply(lambda x: round(x, 2))

In [5]:
df

    sales  prev_sales     inc
0     100         NaN     NaN
1     150       100.0   50.00
2     150       150.0    0.00
3     120       150.0  -20.00
4     135       120.0   12.50
5     180       135.0   33.33
6     230       180.0   27.78
7     500       230.0  117.39
8     501       500.0    0.20
9     499       501.0   -0.40
10    500       499.0    0.20
11    500       500.0    0.00